### ISSUE TITLE
BTD Battles flash not saving tower unlocks, battlescore, etc.

### ISSUE THREAD

**Issue by sonicfan888** [GlennnM/FlashPrivateServer#2]
whenever i reopen battles flash all my tower unlocks are gone and battlescore is reset. is this intentional or is this just a false bug idk

**Comment by GlennnM** [comment]
It's caused by ninja kiwi hosting those stats on a separate server which is still running but doesn't seem to get updated
Tower unlocks should stay though(at least if you buy the tier 4 for that tower), but obviously this isn't ideal so eventually it might just include a client mod with all unlocks built in

**Comment by sonicfan888** [comment]
so technically i need to get that tier 4 for the tower that i just unlocked to save that tower?
