### ISSUE TITLE
Sas4 Event weapon bug

### ISSUE THREAD

**Issue by MiniTez** [GlennnM/FlashPrivateServer#6]
![Screenshot 2024-12-06 070020](https://github.com/user-attachments/assets/ae325ed6-e12e-4909-b4f7-3f7cc5d1cbd4)
![Screenshot 2024-12-06 070035](https://github.com/user-attachments/assets/df5ef686-21b3-46e0-87d4-4bc94500493c)
I received a Christmas version of the Easter weapon Peter's Hottentail, during the Christmas event.

**Comment by GlennnM** [comment]
Similar weapons to these were created in the past because nk continually uses the wrong event id's, if these variants are not all added to the list then the game will crash for people who have those weapons. So in order to avoid crashing, the game could have been modded so all of these guns are reverted to normal holiday guns, or so that the variants(some of which are very old i.e. christmas 3100) are kept by making all of them valid, and the 2nd option was chosen.

The other advantage of the 1st fix is vanilla compatibility, which if it actually worked would be worth considering, but due to the changing id's the only way to get actual vanilla compatibility is just to delete all holiday guns.
